# -*- coding: utf-8 -*-
"""Copy of Tugas Minggu 14 - Spark MLlib - Ony.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16VhfqRc3M65-7sVPCRBwDQNb2BsUdkIR

## Ony Novianti
#### 2041720029 (TI-3A)
"""

# Sumber : https://github.com/cloudxlab/bigdata/blob/master/spark/examples/mllib/ml-recommender.scala

# Connect Google Drive Untuk Ambil Data
from google.colab import drive
drive.mount('/content/drive')

# Install PySpark
!pip install pyspark

# Import Library
from pyspark.mllib.stat import Statistics
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("Movie Lens").getOrCreate()
sc = spark.sparkContext

# Data Untuk Dihitung
raw = sc.textFile("/content/drive/MyDrive/TI-3A/ml-1m/ratings.dat")

def parseRating(row):
    fields = row.split("::")
    return float(fields[2])

ratings = raw.map(parseRating)

# Diambil dari ratings.dat
mat = ratings.map(lambda x: [x])

# Perhitungan Statistics
summary = Statistics.colStats(mat)
print("Mean:", summary.mean()[0])
print("Variance:", summary.variance()[0])
print("Number of Non-Zeros:", summary.numNonzeros()[0])

